import { z } from 'zod';
import type { AgentActivityEvent, AgentMessage, AgentSession, AgentStreamChunk, Bootstrap, Model, ModelPreferences, PermissionPolicy, PermissionRequest, PermissionRule, Project, Provider, ProviderAccount, ProviderAccountInfo, SessionChange, SessionChanges, SessionFileDiff, Tool, ToolCall, ToolOutputChunk, ToolResult, UsageRecord, Workspace } from '../types/domain';

const count = z.number().int().nonnegative();
const decision = z.enum(['allow', 'ask', 'deny']);
export const permissionModeSchema = z.enum(['ask', 'workspace_write', 'full_access']);
export const permissionCategorySchema = z.enum(['read', 'write', 'command', 'network', 'dangerous']);
export const permissionSchema: z.ZodType<PermissionPolicy> = z.object({ mode: permissionModeSchema.default('ask'), readFiles: decision, git: decision, writeFiles: decision, shell: decision, externalFiles: decision.default('ask'), maxToolRounds: count });
export const permissionRequestSchema: z.ZodType<PermissionRequest> = z.object({ categories: z.array(permissionCategorySchema), summary: z.string(), reason: z.string(), canAlwaysAllow: z.boolean() });
export const permissionRuleSchema: z.ZodType<PermissionRule> = z.object({ id: z.string(), projectId: z.string(), categories: z.array(permissionCategorySchema), summary: z.string(), createdAt: z.string() });
export const modelSchema: z.ZodType<Model> = z.object({ id: z.string(), provider: z.string(), displayName: z.string(), apiProtocol: z.enum(['preview', 'open_ai_responses', 'open_ai_chat', 'anthropic', 'gemini']).nullable().default(null), capabilities: z.array(z.enum(['tools', 'vision', 'reasoning', 'streaming'])), supportsTools: z.boolean(), supportsVision: z.boolean(), supportsReasoning: z.boolean(), supportsStreaming: z.boolean(), contextWindow: count.nullable(), inputPrice: z.number().nonnegative().nullable(), outputPrice: z.number().nonnegative().nullable(), status: z.enum(['available', 'deprecated', 'unavailable']) });
export const modelReferenceSchema = z.object({ providerId: z.string(), modelId: z.string() });
export const modelPreferencesSchema: z.ZodType<ModelPreferences> = z.object({ defaultModel: modelReferenceSchema.nullable(), favorites: z.array(modelReferenceSchema), recent: z.array(modelReferenceSchema) });
export const providerSchema: z.ZodType<Provider> = z.object({ id: z.string(), name: z.string(), protocol: z.enum(['preview', 'open_ai_responses', 'open_ai_chat', 'anthropic', 'gemini']), baseUrl: z.string().nullable(), models: z.array(modelSchema), connected: z.boolean().default(false) });
export const providerAuthMethodSchema = z.enum(['api_key', 'google_oauth', 'openai_chatgpt']);
export const providerAccountSchema: z.ZodType<ProviderAccount> = z.object({
  providerId: z.string(), providerName: z.string(), state: z.enum(['not_connected', 'connected', 'needs_attention']),
  authMethod: providerAuthMethodSchema.nullable(), accountLabel: z.string().nullable(), connectedAt: z.string().nullable(),
  lastValidatedAt: z.string().nullable(), lastErrorCode: z.string().nullable(), availableMethods: z.array(z.object({
    method: providerAuthMethodSchema, label: z.string(), available: z.boolean(), unavailableReason: z.string().nullable(),
  })),
});
export const providerAccountInfoSchema: z.ZodType<ProviderAccountInfo> = z.object({ providerId: z.string(), providerName: z.string(), authMethod: providerAuthMethodSchema, accountLabel: z.string() });
export const toolSchema: z.ZodType<Tool> = z.object({ name: z.string(), description: z.string(), permission: z.enum(['read_files', 'git', 'write_files', 'shell', 'user_interaction']), riskLevel: z.enum(['low', 'medium', 'high', 'critical']), timeoutMs: count, parallelSafe: z.boolean().default(false), inputSchema: z.record(z.string(), z.unknown()) });
export const toolCallSchema: z.ZodType<ToolCall> = z.object({ id: z.string(), name: z.string(), arguments: z.record(z.string(), z.unknown()) });
export const toolResultSchema: z.ZodType<ToolResult> = z.object({ toolCallId: z.string(), name: z.string(), content: z.string(), isError: z.boolean(), durationMs: count, structuredContent: z.record(z.string(), z.unknown()).or(z.array(z.unknown())).nullable().default(null) });
export const messageSchema: z.ZodType<AgentMessage> = z.object({ id: z.string(), role: z.enum(['system', 'user', 'assistant', 'tool']), content: z.string(), toolCalls: z.array(toolCallSchema), toolResult: toolResultSchema.nullable(), createdAt: z.string(), providerData: z.unknown() });
const agentActivitySchema: z.ZodType<AgentActivityEvent> = z.object({ id: z.string(), sessionId: z.string(), kind: z.enum(['plan', 'progress', 'tool_started', 'tool_completed', 'file_inspected', 'search_performed', 'command_executed', 'file_edited', 'test_run', 'context_compacted']), summary: z.string(), toolCallId: z.string().nullable(), createdAt: z.string() });
const workingContextSchema = z.object({ objective: z.string().default(''), decisions: z.array(z.string()).default([]), repositoryFacts: z.array(z.string()).default([]), implementationState: z.string().default(''), outstandingTasks: z.array(z.string()).default([]), protectedInstructions: z.array(z.string()).default([]), compactedThrough: z.string().nullable().default(null), compactedTurns: count.default(0) }).default({ objective: '', decisions: [], repositoryFacts: [], implementationState: '', outstandingTasks: [], protectedInstructions: [], compactedThrough: null, compactedTurns: 0 });
export const sessionSchema: z.ZodType<AgentSession> = z.object({ id: z.string(), projectId: z.string(), providerId: z.string(), modelId: z.string(), title: z.string(), status: z.enum(['queued', 'planning', 'working', 'waiting_for_permission', 'waiting_for_user', 'completed', 'failed', 'cancelled']), messages: z.array(messageSchema), permissionPolicy: permissionSchema, pendingToolCall: toolCallSchema.nullable().default(null), pendingPermission: permissionRequestSchema.nullable().default(null), sessionPermissionGrants: z.array(z.string()).default([]), oneTimePermissionGrants: z.array(z.string()).default([]), pendingUserInput: toolCallSchema.nullable().default(null), queuedToolCalls: z.array(toolCallSchema), iterations: count.default(0), toolCalls: count.default(0), activityEvents: z.array(agentActivitySchema).default([]), createdAt: z.string(), updatedAt: z.string(), error: z.string().nullable(), toolRounds: count, archivedAt: z.string().nullable().default(null), gitBranch: z.string().nullable().default(null), workspaceMode: z.enum(['direct', 'isolated']).default('direct'), baseBranch: z.string().nullable().default(null), worktreePath: z.string().nullable().default(null), workingContext: workingContextSchema.default({ objective: '', decisions: [], repositoryFacts: [], implementationState: '', outstandingTasks: [], protectedInstructions: [], compactedThrough: null, compactedTurns: 0 }), projectInstructionFiles: z.array(z.string()).default([]) });
export const agentStreamChunkSchema: z.ZodType<AgentStreamChunk> = z.object({ sessionId: z.string(), delta: z.string(), reset: z.boolean() });
export const toolOutputChunkSchema: z.ZodType<ToolOutputChunk> = z.object({ sessionId: z.string(), toolCallId: z.string(), stream: z.enum(['stdout', 'stderr']), chunk: z.string() });
export const projectSchema: z.ZodType<Project> = z.object({
  id: z.string(), workspaceId: z.string(), name: z.string(), path: z.string(), repositoryRoot: z.string().nullable(), activeBranch: z.string().nullable(), lastOpenedAt: z.string(), projectInstructions: z.string(), preferredModel: z.string().nullable(), permissions: permissionSchema, isRecent: z.boolean(), createdAt: z.string(),
});
export const projectFileSchema: z.ZodType<import('../types/domain').ProjectFileEntry> = z.object({ name: z.string(), path: z.string(), kind: z.enum(['file', 'directory']), sizeBytes: count, isSymlink: z.boolean() });
export const changedFileSchema: z.ZodType<import('../types/domain').ChangedFile> = z.object({ path: z.string(), status: z.string() });
export const sessionChangeSchema: z.ZodType<SessionChange> = z.object({ path: z.string(), kind: z.enum(['added', 'modified', 'deleted']), additions: count, deletions: count, preexistingStatus: z.string().nullable(), staged: z.boolean(), unstaged: z.boolean(), conflicted: z.boolean(), canStage: z.boolean(), reviewed: z.boolean() });
export const sessionChangesSchema: z.ZodType<SessionChanges> = z.object({ sessionId: z.string(), files: z.array(sessionChangeSchema), additions: count, deletions: count, testsSummary: z.string().nullable(), workingTree: z.enum(['clean', 'modified']), baselineHead: z.string().nullable(), baselineAt: z.string() });
export const sessionFileDiffSchema: z.ZodType<SessionFileDiff> = z.object({ path: z.string(), diff: z.string(), binary: z.boolean(), conflicted: z.boolean() });
export const languageCountSchema: z.ZodType<import('../types/domain').LanguageCount> = z.object({ name: z.string(), files: count });
export const projectOverviewSchema: z.ZodType<import('../types/domain').ProjectOverview> = z.object({ projectId: z.string(), repositoryRoot: z.string().nullable(), activeBranch: z.string().nullable(), gitStatusAvailable: z.boolean(), isDirty: z.boolean(), changedFiles: z.array(changedFileSchema), repositorySizeBytes: count, scanLimited: z.boolean(), languages: z.array(languageCountSchema) });
export const taskWorktreeSchema: z.ZodType<import('../types/domain').TaskWorktree> = z.object({ sessionId: z.string(), title: z.string(), branch: z.string(), baseBranch: z.string(), taskStatus: z.enum(['queued', 'planning', 'working', 'waiting_for_permission', 'waiting_for_user', 'completed', 'failed', 'cancelled']), available: z.boolean(), dirty: z.boolean(), hasCommittedChanges: z.boolean(), changedFiles: z.array(changedFileSchema), conflicts: z.array(z.string()), additions: count, deletions: count });
export const taskWorktreeActionSchema: z.ZodType<import('../types/domain').TaskWorktreeAction> = z.object({ worktree: taskWorktreeSchema.nullable(), conflicts: z.array(z.string()), message: z.string() });
export const terminalResultSchema: z.ZodType<import('../types/domain').TerminalResult> = z.object({ output: z.string(), exitCode: z.number().int().nullable(), timedOut: z.boolean() });
export const workspaceSchema: z.ZodType<Workspace> = z.object({ id: z.string(), name: z.string(), projects: z.array(projectSchema) });
export const usageSchema: z.ZodType<UsageRecord> = z.object({ id: z.string(), sessionId: z.string(), projectId: z.string().default(''), providerId: z.string(), modelId: z.string(), inputTokens: count, usageAvailable: z.boolean().default(true), cachedInputTokens: count.nullable().default(null), outputTokens: count, costUsd: z.number().nullable(), durationMs: count, success: z.boolean().default(true), failureCode: z.string().nullable().default(null), createdAt: z.string() });
export const bootstrapSchema: z.ZodType<Bootstrap> = z.object({ workspace: workspaceSchema, providers: z.array(providerSchema), accounts: z.array(providerAccountSchema), sessions: z.array(sessionSchema), usage: z.array(usageSchema), tools: z.array(toolSchema), permissionPolicy: permissionSchema, modelPreferences: modelPreferencesSchema });
